name: Automerge feature branch
on:
  push:
    branches: [ 'hu**' ]
jobs:
  pre-merge:
    name: Pre-merge
    runs-on: ubuntu-latest
    steps:
      - name: Verificar palabra clave en commit
        run: |
          if startsWith(github.event.head_commit.message, 'feat'); then
            echo "El commit contiene la palabra clave 'feat'"
            exit 0
          else
            echo "El commit no contiene la palabra clave 'feat'"
            exit 1
          fi
      - name: Actualizar feature branch con main
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: refs/heads/main
          target-branch: ${{ github.ref }}
  test:
    needs: pre-merge
    name: Pruebas
    runs-on: ubuntu-latest
    steps:
      - name: Checkout de repositorio
        uses: actions/checkout@v2
      - name: Configuración de entorno de python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Instalación de librerías y dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Correr pruebas
        id: correr-pruebas
        run: python -m unittest
      - name: Cálculo de cubrimiento
        id: cubrimiento
        run: |
            coverage run -m unittest
            coverage report -m
  merge:
    needs: test
    name: Integración de feature branch
    runs-on: ubuntu-latest
    steps:
      - name: Integrar feat-branch a main
        if: ${{ success() }}
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: ${{ github.ref }}
          target-branch: refs/heads/main