name: Push feature branch
on:
  push:
    branches: [ 'hu**' ]
jobs:
  pre-push:
    name: Pasos previos
    runs-on: ubuntu-latest
    steps:
      - name: Validar palabra clave en commit
        if: ${{ !startsWith(github.event.head_commit.message, 'Paso') }}
        run: |
          echo "El commit no contiene la palabra clave 'Paso'"
          exit 1
      - name: Actualizar feat branch
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: refs/heads/main
          target-branch: ${{ github.ref }}
  test:
    needs: pre-push
    name: Pruebas
    runs-on: ubuntu-latest
    steps:
      - name: Checkout de repositorio
        uses: actions/checkout@v2
      - name: Configuración de entorno de python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Instalación de librerías y dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Correr pruebas
        id: correr-pruebas
        run: python -m unittest -v tests/test_persona.py
  merge:
    needs: test
    name: Integración de feat branch
    runs-on: ubuntu-latest
    steps:
      - name: Integrar feat-branch -> develop
        if: ${{ success() }}
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: ${{ github.ref }}
          target-branch: refs/heads/main